### ISSUE TITLE
Unable to get reports 

### ISSUE THREAD

**Issue by yshnaviganapathi** [AppiumTestDistribution/appium-reporter-plugin#141]
Installed sharp version 0.31.3 and appium-reporter-plugin. Tried fetching the reports by hitting the server "http://localhost:4723/getReport", but reports are not generated. @Dileep17 Could you help us resolve the issue and get the reports?

Platform: windows 
C:\>npm -v
9.8.1

C:\>node -v
v18.17.0

C:\>appium driver list
√ Listing available drivers
- uiautomator2@2.29.3 [installed (npm)]
- xcuitest@4.33.1 [installed (npm)]

C:\> appium plugin list
√ Listing available plugins
- appium-reporter-plugin@1.1.0-beta.03 [installed (npm)]

C:\>npm ls sharp
`-- sharp@0.31.3

**We are getting this error:**

[HTTP] <-- POST /wd/hub/session 200 13769 ms - 1704
[HTTP]
[HTTP] --> GET /getReport
[HTTP] {}
uncaughtException: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.<anonymous> (C:\Users\vganapa\.appium\node_modules\appium-reporter-plugin\lib\reporter.js:130:39)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\vganapa\.appium\node_modules\appium-reporter-plugin\lib\reporter.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Dileep17** [comment]
@yshnaviganapathi Could provide sample code to reproduce the issue. Would be easy & fast for me to debug and provide resolution.

**Comment by Dileep17** [comment]
@yshnaviganapathi check https://github.com/AppiumTestDistribution/appium-reporter-plugin/tree/main/examples for Java and JS implementation.

Closing this issue.

**Comment by TestVaishnavi** [comment]
@Dileep17 , I tried installing the plugin then 
 activated - appium --use-plugins=appium-reporter-plugin
 mvn test
after successful execution, I don't see the report. May I know in which location it will get downloaded?

**Comment by Dileep17** [comment]
Hi @TestVaishnavi,  report file wont be created by the plugin. 

I hope you are comfortable with JS. Have a look at https://github.com/AppiumTestDistribution/appium-reporter-plugin/blob/main/examples/js/AppiumReportPluginDemo/config/wdio.shared.conf.ts#L62 the response of  `/getReport` should be written to a file (*.html). This would be the report.
