### ISSUE TITLE
When the plugin is loaded, appium test execution (iOS) became around 5X slower

### ISSUE THREAD

**Issue by isaac-tribal** [AppiumTestDistribution/appium-reporter-plugin#60]
Command to load the plugin
`appium --use-plugins=appium-reporter-plugin`

Even if is not calling any function (just loading the plugin), test execution it becomes significantly slower.

**Comment by saikrishna321** [comment]
@isaac-tribal Can you please server logs with timestamp? 

Two versions of server logs - with and without plugin

**Comment by isaac-tribal** [comment]
@saikrishna321 This is the log for a test suite (7 tests),  with more tests added more time (I have around 60 tests)

**First log, without the plugin around 2:25.**

 **18:13:57
-18:11:32
= 2:25**

[appium-whithout-plugin.log](https://github.com/AppiumTestDistribution/appium-reporter-plugin/files/10106500/appium-whithout-plugin.log)

**Second log with the plugin enabled:  around 4:03 (Almost twice)**

  **18:21:58
-18:17:55
= 4:03**

[appium-with-plugin.log](https://github.com/AppiumTestDistribution/appium-reporter-plugin/files/10106515/appium-with-plugin.log)

**Comment by isaac-tribal** [comment]
@saikrishna321 Now with more tests **(28 tests), it takes 5X more:**

 without the plugin **around 12:46**
 18:56:05
-18:43:19
= 12:46

[appium-whithout-plugin_28.log](https://github.com/AppiumTestDistribution/appium-reporter-plugin/files/10107257/appium-whithout-plugin_28.log)


with the plugin enabled: **around 1:06:32 (5X slower)**

 20:14:29
-19:07:57
**= 1:06:32**

[appium-with-plugin_28.log](https://github.com/AppiumTestDistribution/appium-reporter-plugin/files/10107260/appium-with-plugin_28.log)

**Comment by Dileep17** [comment]
@isaac-tribal fixed this as part of PR #109 
Please try `1.0.0-beta.11` and let us know if you still face performance issues. Thanks!

**Comment by isaac-tribal** [comment]
> @isaac-tribal fixed this as part of PR #109 Please try `1.0.0-beta.11` and let us know if you still face performance issues. Thanks!

**Comment by Dileep17** [comment]
kewl. Closing this issue.
