### ISSUE TITLE
Add Pending Tests

### ISSUE THREAD

**Issue by isaac-tribal** [AppiumTestDistribution/appium-reporter-plugin#69]
Appium  client log: 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/73899473/206026093-c78cd1dd-9d20-4504-9215-200d985c7762.png">

Report:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/73899473/206026033-31bcdaa9-5242-4739-b1b4-c4cc1fc1e4f1.png">

**Comment by Dileep17** [comment]
This plugin currently works based on appium session-id. For pending tests session-id won't be created at all hence they won't appear in report. 

Having said that, this is functionally a valid request. Need to refactor the plugin to accommodate this.

**Comment by Dileep17** [comment]
Added Pending and Unknown states to test report
<img width="874" alt="image" src="https://user-images.githubusercontent.com/2680841/218792562-400db472-e42e-4cd6-8a35-7b15740aeba7.png">

Having said that, this plugin just picks the test status that's sent to it via `POST: /session/:sessionId/setTestInfo`.  For skipped tests, it's upon the tests to call `POST: /session/:sessionId/setTestInfo` and pass info. As mentioned in the documentation test status are "PASSED, FAILED, PENDING, All other strings are considered as UNKNOWN"

**Comment by Dileep17** [comment]
@isaac-tribal ^^

**Comment by saikrishna321** [comment]
Its worth to add in ReadMe how to use this endpoint from client

**Comment by Dileep17** [comment]
check the following section mate, https://github.com/AppiumTestDistribution/appium-reporter-plugin#settestinfo

let me know if we can anything more.
