### ISSUE TITLE
html report not opening

### ISSUE THREAD

**Issue by thomasklaush** [AppiumTestDistribution/appium-reporter-plugin#91]
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by dlutfrank** [comment]
same error

**Comment by Dileep17** [comment]
@dlutfrank Could you check with 1.0.0-beta.10 ? 
Would help if you could provide
1. Test example
2. HTML report

**Comment by dlutfrank** [comment]
@Dileep17 everything is ok with 1.0.0-beta.10
