### ISSUE TITLE
garbled characters appear in testName using Chinese

### ISSUE THREAD

**Issue by ZhaoGuan** [AppiumTestDistribution/appium-reporter-plugin#95]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/29194004/213603721-ad82374a-cfb4-4f83-9a8e-c414fdff4e42.png">
How to clear the data in the session?

**Comment by Dileep17** [comment]
This is caused because of the way decoding of testName is done. 
There is no need to decode test name and test status. Removed decoding for those fields fixed this issue. 
Thanks for reporting this @ZhaoGuan . Please install latest version 1.0.0-beta.10 and let us know if your issue is fixed.

**Comment by Dileep17** [comment]
@ZhaoGuan let us know if this is still an issue 
![image](https://user-images.githubusercontent.com/2680841/217528264-c5f631be-95aa-4069-a934-e863f4578de5.png)
![image](https://user-images.githubusercontent.com/2680841/217528305-8cc0a589-84ba-4693-8345-fba7d8d1092a.png)
